version: '3'
services:
  web: 
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /src/app/node_modules
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: development
    networks:
      - app-network
  
networks:
    app-network:
        driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local

